### PR TITLE
The modern mode, "use strict"

### PR DESCRIPTION
**Pull request by JustIzumi**

### CODE REVIEW

**Review by szcsl — COMMENTED** [review]
Hi @JustIzumi!

Thanks for the PR! I appreciate your contribution, but unfortunately, the hungarian translation is awkward on occassions and this can hinder understanding for newbies. 

I am happy to help make it sound more natural, although it will require a bit of a rewrite -- but the PR and the contribution would still be yours. :)

May I comment your PRs?

**Comment by JustIzumi** [comment]
Dear @szcsl 

Thank you for reviewing my pull request! I myself noticed too, that my translation may not be as good as it should be, but I would be more than happy, if you could help me improve it!

**Review by szcsl — CHANGES_REQUESTED** [review]
Apologies for commenting a lot. I tried to honor the initial translation as much as possible, but I have a strong preference for reducing unnecessary constructs. But again, many thanks for taking your time!

I could have merged it and update it myself, but I don't want to hijack your contribution. If you prefer, I can simply merge and update the other PR and any future PRs -- but I think it's fair, to have it merged as your PR. :)

My general guidelines for translations are:
- Think about the point of the original text and try to convey the same message in your own words as clearly and succintly as possible. You don't have to stick with the structure and phrasing of the original text if that would be more verbose or just awkward.
- A nice summary of general guidelines: https://www.accelingo.com/technical-translation-best-practices/

**Review by szcsl — APPROVED** [review]
Thanks for following through! :) I will review the other PR soon.

**Pull request merged**
